EdkRepo: Fix failure in edkrepo sync -u
edkrepo sync -u currently fails with:
ValueError: too many values to unpack (expected 2)

This is due to added items in the RemoteRepo() tuple. The offending line was
creating a variable that was unused and has therefore been deleted.

Signed-off-by: Nate DeSimone nathaniel.l.desimone@intel.com